version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5466:5432' # avoid collision with another pg DB
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
